DIRACGrid/Pilot

- .travis.yml
- Pilot/tests/Test_Pilot.py
- PilotLogger/PilotLogger.py
- README.md
- README.rst
- pytest.ini
- requirements.txt
Added the YML file for Travis, configured so that simultaneous 2.6 and 2.7 are tested. Sadly Travis only supports python >=2.6 otherwise we could also test older versions. 
Had to change PilotLogger since it used dict comprehension and adopt test to be compatible with 2.6
> Enable Travis-CI for Pilot

- .landscape.yml
This is as in the pull request for DIRAC, with the addition of no-self-use. I don't know do you want to use the same .pylintrc as in DIRAC and add an additional flag to .landscape.yml or fix the .pylintrc for no-self-use
pep8:
E111 indentation is not a multiple of four
E114 indentation is not a multiple of four (comment)
> Added configuration of landscape

- Pilot/dirac-pilot.py
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- Pilot/tests/Test_Pilot.py
Discover pilot parameters (Commands, extensions and version) at runtime.
Removed the -X and -E command line options.
The json file is not created if it already exists.
For issue #2724
> Discover pilot parameters (Commands, extensions and version) at runtime.

- Pilot/pilotTools.py
- Pilot/tests/Test_Pilot.py
- Pilot/user_data
This is to get ready for a corresponding change in the pilotSynchronizer to publish all multivalue options in pilot.json as comma-list strings rather some as proper lists, inconsistently. If other projects add pilot commands and corresponding multivalue options in the CS, then everything will then be consistent. It also avoids the need to hardcode multivalue->list processing in the pilotSynchronizer for some options (Commands and CommandExtensions).
There are also a couple of changes to the temporary LHCb code in the user_data file which uploads log files to lhcb-depo.cern.ch until we can use the extended pilot logging for production.
> Handle Commands/Extensions as proper lists or comma lists

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
The one-line change to pilotCommands.py puts the time the Nagios probe was run in the saved results file itself. 
This is needed by check_pilot_results in LHCbSAM, which needs to know the time so it can flag stale results as "unknown".  This mechanism allows the test result files to be migrated or mirrored from one HTTPS server to another without needing to update the file datestamps reported by HTTP Last-Modified header.
> Add test execution time to saved Nagios probe results

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- Pilot/tests/Test_Pilot.py
- Pilot/user_data_sc
- Pilot/user_data_vm
This PR has updates to user_data_vm and adds user_data_sc (for Singularity containers and ok with Docker too).
In pilotCommands.py, the UnpackDev command is removed and a modified version of ReplaceDIRACCode from Pilot 2.0 is used instead. The main change is to use TGZ instead of ZIP, as the ZipFile module does not preserve the execute bit on scripts.
I've tidied up pilotTools.py, in particular ordering the list of options alphabetically, which identified one duplicate ("-C") marked with FIXME. I also removed a duplicate of the __initCommandLine2() function.
The functionality of Pilot 3.0 is otherwise unchanged.
> Changes to user_data_** and replace UnpackDev with ReplaceDIRACCode

- Pilot/pilotTools.py
Matching patch for DIRACGrid/DIRAC/pull/4091: This forces maxNumberOfProcessors to be an int which prevents a min() expression from failing later in the code.
> Ensure maxNumberOfProcessors is int

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- Pilot/user_data_vm
This PR adds support for multiprocessor payloads in DIRAC VMs defined by user_data_vm. In the pilotTools/Commands, self.pp.payloadProcessors and self.pp.pilotProcessors are introduced which are available to other pilot commands (eg MultiLaunchAgent). Required tags and normal tags are now stored in CEDefaults by CheckWN rather than by CheckCE to allow MultiProcessor and NProcessors tags to be created when they have not been created as part of the pilot definition (eg inside a VM.) The MultiLaunchAgent now launches int(P/p) job agents where P is the number of processors allocated to the pilot (or VM) and p is the number of processors per payload.  
In CheckWN, self.cfg is used throughout instead of a mixture of cfg and self.cfg (which I think was just there for historical reasons?)
> Payload processors

- tests/CI/pilot_ci.sh
Apparently pilotLogger flag was on in the tests. By default it was trying to send messages to local file.
I turned that off.
Also,  the stomp/requests function is not necessary in that case
> Remove option to run pilot loggers from tests

- Pilot/user_data_vm
This change is needed for CernVM4/CentOS7 and has been tested with LHCb and GridPP DIRAC at Manchester. 
(It is not urgent that this migrates from devel to master as the user_data_vm file in both cases is not automatically pulled from GitHub. ie I can manually update it on the web servers.)
> Update user_data_vm for CernVM4/CentOS7

- .github/workflows/nightly.yml
- tests/pilot.json
- tests/upload.sh
This PR adds a "nightly" action for uploading the pilot files (in a tarball names pilot.tar) and a pilot.json file to a web server (basically: here https://diracproject.web.cern.ch/diracproject/tars/Pilot/DIRAC/).
The result can be visible in https://diracproject.web.cern.ch/diracproject/tars/Pilot/DIRAC/master/
The pilot.tar and pilot.json files are then used by these tests: https://github.com/DIRACGrid/DIRAC/pull/4392/files
> added nighly for uploading pilot 'tarballs' (for tests)

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
This PR adds options related to `JobAgent` and bound to the `PoolCE` usage:
* `pollingTime`: mainly to reduce the polling time of `JobAgent` as it usually takes 30sec to submit a job to the `PoolCE`. It allows to start running multiple jobs quicker.
* `stopOnApplicationFailure`: boolean that can be set to `False` to avoid `JobAgent` to finish when an error occurs within a job. The `PoolCE` can run several jobs at the same time and we could continue the execution. Moreover, on batch systems, it could avoid to waste allocated time.
* `stopAfterFailedMatches`: same idea
It also removes the `MAX_CYCLES = 10` attribute limiting the number of cycles in `JobAgent` to 10.
As we may encounter some nodes having 24 or even 96 processors where we can run more than 10 jobs, we should be able to set …
> Add JobAgent options: pollingTime, stopAppFailure, stopFailedMatches

- Pilot/pilotCommands.py
Reverts DIRACGrid/Pilot#108
Fails in LHCb with e.g.
```
Traceback (most recent call last):
File "dirac-pilot.py", line 66, in <module>
command.execute()
File "/home/iris/pltlhcb016/home_cream_913165079/CREAM913165079/DIRAC_1G9oWrpilot/pilotCommands.py", line 326, in execute
os.symlink(os.path.join("..", self.pp.localConfigFile), "etc/dirac.cfg")
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
File "<stdin>", line 162, in <module>
File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
onerror(os.rmdir, path, sys.exc_info())
File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/iris/pltlhcb016/home_cream_913165079/CREAM913165079/DIRAC_1G9oWrpilot'
```
@marianne013
> Revert "if etc/dirac.cfg does not exist, create it as a symlink to pilot.cfg"

- Pilot/pilotTools.py
This PR ensures the return value of `executeAndGetOutput` is always valid ascii. Any invalid bytes are replaced with `?`. I've tested this will all sorts of odd locales and Python versions, including 2.6, 2.7 and 3.8. See the screenshot for examples.
In principle something similar could be done for `stderr` but it's only printed to `sys.stdout` so I don't think it's necessary.
Fixes #112
Closes #114
> Ensure pilot command output is always ascii

- Jenkinsfile
- Pilot/dirac-install.py
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- tests/CI/pilot_ci.sh
- tests/CI/utilities.sh
In this PR:
- added function for installing a python3 client
- stop looking for Pilot commands in DIRAC code
- stop supporting older DIRAC versions
todo:
Tests:
- workflow tests:
- submitAndMatch tests
> Install a py3 client + large simplifications

- Pilot/pilotCommands.py
The SSHBatchComputingElement submission was not taken into account. Now it will be indicated by the SSHBATCH_JOBID and SSH_NODE_HOST environment variables.
DIRACOS2 installation is first attempted from the CVMFS and then from Github in case of failure.
> Pilot reference for the SSHBatchCE case + DIRACOS2 installation from CVMFS

- Pilot/pilotCommands.py
/proc/cpuinfo looks quite different on non-x86 CPUs, so its parsing is not working. Maybe it's better to use a python module instead (e.g. the `platform` module)
> fix: fix check for CPU model

- Pilot/pilotCommands.py
LHCb's htcondor pilots started failing with this error due to the tags not being quoted in the command:
```bash
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `dirac-configure pilot.cfg -o /LocalSite/CEType=HTCondorCE -o /LocalSite/ExtraPilotOptions=-M 3 -o /LocalSite/ExtraSubmitString=periodic_remove =  (JobStatus == 4) && (time() - EnteredCurrentStatus) > ( 24 * 3600)'
```
> [master] Quote Tags when generating dirac-configure command

- Pilot/pilotCommands.py
As this is becoming common, avoids having hundreds of lines of output on many core machines.
> [devel] Group CPU info

- Pilot/pilotCommands.py
pilotCommands: purge installEnv before updating values from diracosrc. Fixes #156 
Otherwise variables unset in diracosrc just remain in installEnv
PS: Not clear to me if this should go to devel or master.
> pilotCommands: purge installEnv before updating values from diracosrc

- Pilot/pilotCommands.py
We have an issue with ARC pilot references interacting with AREX services.
From what I understand, since ARC6, there is a new environment variable providing the pilot reference, which is `GRID_GLOBAL_JOBURL`: https://source.coderefinery.org/nordugrid/arc/-/merge_requests/1017
`GRID_GLOBAL_JOBID` now provides only the ID of the job and not the full URL like before (with gridftp).
Because of that, pilots set the `PilotReference` attribute to : `<ARCID>` instead of `https://<ARCINSTANCE>:<PORT>/rest/1.0/<ARCID>`, which prevents associations between the pilot and the jobs.
> fix: correcting ARC pilot references

- Pilot/pilotTools.py
@fstagni @martynia 
Simon had a go at trying to make the pilot write its log file on a rolling basis. I tested it and as far as I can tell it doesn't break anything. 
This might be a good stepping stone towards handling the output in the pilot logger.
> [devel] feat: implement rolling pilot log output

- Pilot/pilotCommands.py
Fixes an issue introduced with #155
> [devel] Strip new lines before parsing output of dirac-resource-get-parameters

- Pilot/pilotCommands.py
> [devel] Strip new lines before parsing output for more DIRAC commands

- Pilot/pilotTools.py
In #155 there is an issue that if `stdout` is very long and `stderr` is very short only the first 2048 characters will be read from `stdout`.
Instead this PR fixes and keeps the rolling output it by switching the non-blocking IO (as well as making a few clean ups).
> Fix executeAndGetOutput

- Pilot/pilotTools.py
#172 seems to have worked so cherry-pick to master:
https://github.com/DIRACGrid/DIRAC/actions/runs/3523994471/jobs/5909403317
> [master] Cherry pick executeAndGetOutput fix

- Pilot/pilotTools.py
- tests/CI/pilot_newSchema.json
This is a fix to get a VO name from a` wnVO` command line switch. The switch was moved to __initCommandLine1() from __initCommandLine2() so it is analysed before JSON is parsed. The` VO` name, normally obtained from a proxy or from `DIRAC_PILOT_VO` env variable  is required in `__initJSON2()` to get the release version from a VO-specific JSON section.
Notes:
1. Remote logger was disabled for `dteam` to allow Jenkins tests to run, otherwise the message sender would attempt to contact the DIRAC server which does not have this functionality yet.
2. Furthermore If the remote logger is enabled, the sender fails since no proxy/CA is defined in the test:[(https://github.com/DIRACGrid/Pilot/blob/acd5754e041410e5bd99dd62f5c1c820b0186360/Pilot/pilotTools.py#L472 …
> [devel] Remote Pilot Logger to Tornado new JSON format (VO name fix)

- Pilot/dirac-pilot.py
- Pilot/pilotCommands.py
2 fixes:
- include early logs collected up to the point when a remote logger is enabled
- fix a finaliser: it was called by mistake at the end of each command
> [devel] Fixing the log finaliser. Fix early logs which were missing. 

- Pilot/pilotCommands.py
@VladimirRomanovsky reported that LHCbDIRAC pilots always try to write to CVMFS:
```log
2023-04-13T06:30:52.815571Z INFO [CheckCECapabilities] Executing command dirac-configure pilot.cfg -o /LocalSite/CEType=ARC -o /LocalSite/SubmissionMode=Direct -o /LocalSite/MaxRAM=131072 -o /LocalSite/MaxTotalJobs=1 -o /LocalSite/VO='lhcb, LHCb' -o /LocalSite/Queue=nordugrid-SLURM-lhcb -o /LocalSite/MaxWaitingJobs=1 -o /LocalSite/SI00=2775 -o /LocalSite/architecture=x86_64 -o /LocalSite/maxCPUTime=6000 -o /LocalSite/wnTmpDir=/tmp -o /LocalSite/OS=ScientificCERNSLC_Carbon_6.9 -o /LocalSite/Pilot=True -FDMH
WARNING: Parsing of '.cfg' files as command line arguments is changing!
Set the environment variable 'export DIRAC_NO_CFG=1' to pass the file as a positional
argument (this will become the default). …
```
> [master] Set cfg file to modify in CheckCECapabilities

- Pilot/pilotCommands.py
- `CREAM` and `GLOBUS` are not used anymore
- `OSG`: what is this?
- `ARC`: `GRID_GLOBAL_JOBURL` is always present
> remove: old variables from setFlavour()

- Pilot/pilotTools.py
Add a `/<voname>/Pilot` path element to be searched  for when pilot.json is parsed.
> [devel] add a pathelement to be searched for in pilot.json

- .github/workflows/integration.yml
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- tests/CI/pilot_newSchema.json
- tests/CI/pilot_oldSchema.json
This PR adds few integration test for the pilot:
1. The test simply installs the Pilot, getting configuration from lbcertifdirac70. The matrix variables are right now the python version (the version found on the WN) and the release version, for which here we take the `HEAD` of `rel-v8r0` and `integration` branches of DIRAC. More variables to this matrix can be added, if felt requested.
2. A test where DIRAC is sourced from CVMFS
3. A test for pilot that is installed and then tries to match a job (from lbcertifdirac70)
4. A test where DIRAC is sourced from CVMFS and tries to match a job
5. A integration test for the LHCb extension
6. A integration test for the LHCb extension, but using the vanilla Pilot DIRAC installer
These tests are only run on "push", so not in the pull requests (for a …
> test: adding integration tests

- Pilot/dirac-pilot.py
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- Pilot/tests/Test_simplePilotLogger.py
Added a timer which runs in a separate thread and flushed a remote logger buffer periodically. The timer can be disabled and in this case the buffer will be flushed when full as before.
> [devel] feat: add log flushing with a timer.

- Pilot/pilotCommands.py
Aims at "solving" https://github.com/DIRACGrid/Pilot/issues/197
Currently:
- `tags`/`reqtags` are present in two different locations in the configuration: 
- `/LocalSite`: can contain many times the same tags
- `/Resources/Computing/CEDefaults`: tags are "filtered" such as duplicates are removed
In this PR:
- `tags`/`reqtags` are only present in `/Resources/Computing/CEDefaults`
> devel: pass tags to the Pilot config only once

- Pilot/dirac-pilot.py
- Pilot/pilotTools.py
- Pilot/tests/Test_simplePilotLogger.py
Fix the logic when a remote logger is activated. There are 2 options in the CS:
- RemoteLoggerURL
- RemoteLogging flag
The remote logger is activated when the URL` is not None` and the flag is set to `True`.
The logic before was kinda broken, a disabled remote logger would not emit remote messages(OK) and it would act as a classic logger (OK) but caused problems when a timer was introduced and was not correctly canceled.
> [devel] fix RemoteLogger activation logic; pilot logger timer fixes

- .github/workflows/integration.yml
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- Pilot/tests/Test_Pilot.py
- Pilot/tests/Test_proxyTools.py
- Pilot/tests/Test_simplePilotLogger.py
- tests/CI/pilot_newSchema.json
> Remote logging test -- and partial fixes.

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
This PR potentially makes it optional the specification of "preinstalledEnv" or "preinstalledEnvPrefix". 
If the deployment on CVMFS follows the "standard" setup of: `$location/{releaseProject}dirac/$version/$platorm/diracosrc` then adding `CVMFS_locations` list would be enough.
Loosely connected to https://github.com/DIRACGrid/DIRAC/pull/7359
> Guess location of CVMFS deployed installation

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
Aims at solving https://github.com/DIRACGrid/DIRAC/issues/7177
Associated with https://github.com/DIRACGrid/DIRAC/pull/7289
> [devel] Collect batch system info

- Pilot/dirac-pilot.py
- Pilot/pilotTools.py
- tests/CI/pilot_newSchema.json
In a process of addressing the issue https://github.com/DIRACGrid/DIRAC/issues/7411#issue-2092506573 enable remote logging for selected CEs only. Also allow to vary a buffer size to limit number of remote calls to Tornado server.
> [devel] Remote logging: modify logger buffer size and implement CE white list (address Dirac #7411)

- Pilot/dirac-pilot.py
- Pilot/pilotTools.py
A pilot site changes requires to pass a VO name withing a `sendMessage` call to be used by a server if the name cannot be guessed form a client group. Requires a change in Dirac to accept the new method argument.
> [devel] send a VO name with a log message (address issue #229

- Pilot/pilotCommands.py
Goes with https://github.com/DIRACGrid/DIRAC/pull/7467
> BatchSystemInfo instead of BatchSystem

- Pilot/pilotTools.py
Integration tests in https://github.com/fstagni/Pilot/actions/runs/8005354471/job/21864590900
> fix: give priority to CVMFS locations

- Pilot/pilotTools.py
Pilots submitted to AREX and running through HTCondor under the hoods do not always have the `CONDOR_JOBID` variable set. This is not even part of the official documentation.
I picked up an environment variable from the documentation instead: https://htcondor.readthedocs.io/en/latest/users-manual/env-of-job.html#extra-environment-variables-htcondor-sets-for-jobs
From what I have observed so far, it is always present.
We should have less "`Unknown`" batch systems.
> [devel] fix: use another environment variable to spot pilots running in htcondor

- Pilot/pilotTools.py
Currently in the Cloud CE case the pilot reference is set to the pilot stamp while a "proper" reference is also defined.
> Define properly the pilot reference in the cloud case

- tests/CI/PilotLoggerTest.cfg
This file (`PilotLoggerTest.cfg`) is not used at all in the code, and furthermore is a malformed file.
See (this documentation)[https://github.com/DIRACGrid/diraccfg/] about cfg files.
> fix: Removed malformed and unused cfg

- .github/workflows/integration.yml
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- tests/CI/pilot_newSchema.json
Move from [DIRAC's `dirac-platform` command](https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/Core/scripts/dirac_platform.py).
> Transform configure architecture command to avoid using `dirac-platform` command
