DIRACGrid/Pilot

- .travis.yml
- README.rst
- pytest.ini
- requirements.txt
> Enable coveralls and Landscape

- Pilot/dirac-pilot.py
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- Pilot/tests/Test_Pilot.py
- Pilot/user_data
These changes are a manual rebase of pilotCommands.py and pilotTools.py to the current DIRAC integration branch, and an import of changes for VMs from my temp-diracpilot in GitLab including the MultiLaunchAgent. A key element is an extended format for the file pilot.json which is intended to be fetched along with the pilot code, after being created by pilotSynchronizer.py. I've tried to remove LHCb specifics wherever possible at this stage.
> Import updates for VMs and MultiLaunchAgent

- Pilot/dirac-pilot.py
- Pilot/pilotTools.py
Matching pull request for DIRACGrid/DIRAC#3352.
> Clear PYTHONPATH by default when the pilot starts

- Pilot/pilotCommands.py
- tests/CI/pilot_ci.sh
From https://github.com/DIRACGrid/DIRAC/pull/3441/files
> Portings of tags recognitions

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
Hi,
This is the PR equivalent to DIRACGrid/DIRAC#3510 ported to pilot 3.
Regards,
Simon
> Fix RequiredTag list in pilot commands too

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- tests/CI/pilot_ci.sh
> Portings for MaxRAM and numberOfProcessors

- Pilot/pilotCommands.py
Add the singularity options to local CE to be consistent with pilot 2.0, see more details at <https://github.com/DIRACGrid/DIRAC/pull/3693>
> Add the singularity options to local CE

- Pilot/dirac-install.py
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- Pilot/tests/Test_Pilot.py
- tests/CI/pilot_ci.sh
- tests/CI/utilities.sh
From https://github.com/DIRACGrid/DIRAC/pull/3923
> calling --cleanPYTHONENV option of dirac-install

- Pilot/MessageSender.py
- Pilot/PilotLogger.py
- Pilot/PilotLoggerTools.py
- Pilot/tests/Test_MessageSender.py
- Pilot/tests/Test_PilotLogger.py
- Pilot/tests/Test_PilotLoggerTools.py
- setup.cfg
Refactored PilotLogger  version that was somehow overwritten by older versions. 
Also, add config file with autopep8 settings.
> Add PilotLogger version that was somehow lost in merging

- Pilot/dirac-install.py
port changes from DIRACGrid/DIRAC#3992
> dirac-install: do not set REQUESTS_CA_BUNDLE in bashrc

- .landscape.yml
- .travis.yml
- Jenkinsfile
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- tests/CI/pilot_ci.sh
> Added option to install with DIRACOS

- Pilot/pilotTools.py
> Interpreting a LocalCEType

- Jenkinsfile-PilotWrapper
(used in https://jenkins-dirac.web.cern.ch/blue/organizations/jenkins/PilotWrapper/activity)
> JenkinsFile for pilot wrapper tests

- Jenkinsfile
- Jenkinsfile-CVM4
- Jenkinsfile-PilotWrapper
- Pilot/dirac-install.py
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- tests/CI/pilot.json
Used for MP jobs. This goes together with https://github.com/DIRACGrid/DIRAC/pull/4175
> Setting pilotProcessors to what returned by dirac-wms-get-wn-parameters

- Pilot/pilotCommands.py
Hi @fstagni,
Here is an updated version of the @marianne013 dirac.cfg patch with more code to check that the destination looks sensible. Would it be possible for you to try this with the LHCb set-up?
Regards,
Simon
> Create dirac.cfg (more carefully)

- Jenkinsfile
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- tests/CI/pilot_ci.sh
For fixing https://github.com/DIRACGrid/DIRAC/issues/4686
> make sure warnings/errors from DIRAC scripts are not parsed

- .github/workflows/basic.yml
- tests/CI/pilot.json
- tests/CI/pilot_ci.sh
- tests/CI/utilities.sh
Needs https://github.com/DIRACGrid/DIRAC/pull/4716
> submitAndMatch test will run on several CEs

- Pilot/MessageSender.py
- Pilot/PilotLogger.py
- Pilot/PilotLoggerTools.py
- Pilot/dirac-pilot.py
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- Pilot/tests/Test_MessageSender.py
- environment-py3.yml
- tests/CI/pilot_ci.sh
Also: 
- added `--cfg` switch when possible (when the DIRAC release is over v7r0p29)
- added environment-py3.yml
> Added possibility to bind the WN to a VO

- Pilot/pilotCommands.py
> Revert "set DIRACSYSCONFIG env variable to pilot.cfg"

- tests/CI/pilot_ci.sh
- tests/CI/utilities.sh
Use correct location for pip bootstrap
> fix pip bootstrap

- Pilot/dirac-install.py
- Pilot/pilotCommands.py
- For #131 
- Add support for https://github.com/DIRACGrid/DIRAC/pull/5256
> [master] supporting GPUs, and removed setting XRD_RUNFORKHANDLER

- Pilot/dirac-install.py
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
solves #113 
@zhangxiaomei Have a look, IIUC this is what you want
> [master] feat: added possibility to add a user-defined global defaults, from the pilot options

- .github/workflows/basic.yml
- Pilot/dirac-install.py
@iueda @hmiyake I think this is what you mentioned some time ago... (and I forgot until now).
Please review.
> fix: follow https://github.com/DIRACGrid/management/pull/50

- Pilot/pilotCommands.py
This PR adds the possibility to run `pip install DIRAC` from a generic URI. The mechanism used is simply an extension of the "modules" one, meaning we can do (as before) `pip install git+https://github.com/fstagni/DIRAC.git@mybranch#egg=DIRAC[pilot]` or, for example `pip install /some/path/[pilot]` which basically adds support for pip installing a package that is on CVMFS.
> [devel] Pip install from URI

- Pilot/dirac-install.py
Part of the fix for https://github.com/DIRACGrid/DIRAC/issues/5968.
> Ensure LANG env is set in bashrc

- Pilot/pilotCommands.py
This PR limits the resources used during installation to what the pilot actually owns. It uses the `maxNumberOfProcessors` with a default of `1`; both `self.pp.payloadProcessors` and `self.pp.pilotProcessors` are not available during default command order.
Closes #189.
> Limit Mamba concurrency during installation

- .github/workflows/basic.yml
- Pilot/pilotCommands.py
- Pilot/pilotTools.py
Same as https://github.com/DIRACGrid/Pilot/pull/196 but for `devel` branch
> [devel] add new command RegisterPilot (second attempt)

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
- pyproject.toml
Same as https://github.com/DIRACGrid/Pilot/pull/201 but `devel` branch
> [devel]  Small refactor to increase adaptability 

- Pilot/pilotTools.py
- tests/CI/pilot_newSchema.json
Integration tests: https://github.com/fstagni/Pilot/actions/runs/8078570344
> fix: CVMFS locations comes as a string

- Pilot/pilotCommands.py
- Pilot/pilotTools.py
> fix: removed which command (PATH might not be there after all)

- Pilot/pilotTools.py
Integration tests running in https://github.com/fstagni/Pilot/actions/runs/13989421684
This should fix issue with py2 (see e.g. https://github.com/DIRACGrid/DIRAC/actions/runs/13987969143/job/39165317378?pr=8097)
> fix: ensure unicode conversion

- Pilot/pilotTools.py
> Robin fix ps

- .github/workflows/integration.yml
tests should be OK when the latest releases will be in CVMFS
> test: using a proxy instead of the certificate
